### ISSUE TITLE
Correcciones - QMP1

### ISSUE THREAD

**Issue by ggallici** [RaniAgus/dds-jv-2022-que-me-pongo#1]
Buenas Agustín, como va? En líneas generales cumpliste bastante bien con los requerimientos. Te marco algunas cositas que ví:

- La solución que encontraste no asegura que no existan tipos de prendas inconsistentes con su categoría. Para esto podrías:
    - O bien validar las categorías permitidas para cada nombre de tipo al momento de construir el `TipoPrenda`.
    - O bien pasar a `enum` el `TipoPrenda` y ya tener definido para cada posible tipo su correspondiente categoría.
- Finalmente, ojo con usar `lombok`. Para los TPAs/TPIs no está permitido.

**Comment by RaniAgus** [comment]
¡Gracias! Al final me decidí por el `enum` que es más simple, ahí dejé subidos los cambios. Saludos 😄
